---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: acs-hub
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: acs-hub
  labels:
    name: acs-hub
    cloud: Other
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: gitops-clusters
spec:
  hubAcceptsClient: true
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: auto-import-secret
  namespace: acs-hub
stringData:
  autoImportRetry: "2"
  token: cluster-api-token
  server: https://api.acs.etbit.io:6443
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: cluster-api-token
  namespace: acs-hub
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: auto-import-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: CLUSTER_API_TOKEN
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: acs-hub
  namespace: acs-hub
spec:
  clusterName: acs-hub
  clusterNamespace: acs-hub
  clusterLabels:
    name: acs-hub
    cloud: Other
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: gitops-clusters
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
