apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-acs
  namespace: openshift-gitops
spec:
  clusterSets:
  - acs-clusters
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: acs-gitops
              operator: In
              values:
                - local.acs